### PR TITLE
Follow crystal 1.0.0

### PR DESCRIPTION
**Pull request by kachick**
Without this change makes following error in running spec...

```console
$ crystal --version
Crystal 1.0.0 (2021-03-22)

LLVM: 9.0.1
Default target: x86_64-apple-macosx

$ shards --version
Shards 0.14.1 (2021-03-10)

$ shards --ignore-crystal-version
Resolving dependencies
Fetching https://github.com/sdogruyol/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Installing radix (0.3.8)
Installing kilt (0.4.0)
Installing exception_page (0.1.1)
Installing kemal (0.25.1)
Writing shard.lock
Shard "exception_page" may be incompatible with Crystal 1.0.0
Shard "kemal" may be incompatible with Crystal 1.0.0
Shard "kilt" may be incompatible with Crystal 1.0.0
Shard "radix" may be incompatible with Crystal 1.0.0

$ crystal spec
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'macro_4534319408'

Code in lib/kemal/src/kemal/static_file_handler.cr:1:1

 1 | {% if !flag?(:without_zlib) %}
     ^
Called macro defined in lib/kemal/src/kemal/static_file_handler.cr:1:1

 1 | {% if !flag?(:without_zlib) %}

Which expanded to:

 > 1 |
 > 2 |   require "zlib"
         ^
Error: can't find file 'zlib'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
```

After this change

```console
$ crystal spec
..

Finished in 1.38 milliseconds
2 examples, 0 failures, 0 errors, 0 pending
```

And user using crystal 1.0.0 and shards 0.14.1 raises an error when `--ignore-crystal-version` not given.

So this change might reduce the annoying error for shards users? 🤔

https://github.com/crystal-lang/shards/blob/addc26a3f22fee9fccb01cbb3e8878bef02d4295/docs/shard.yml.adoc

>When just a version number is used it has a different semantic compared to dependencies: x.y.z will be interpreted as ~> x.y, >= x.y.z (ie: >= x.y.z, < (x+1).0.0) honoring semver.

### CODE REVIEW

**Comment by sdogruyol** [comment]
Thank you @kachick, actually we shouldn't include `shard.lock` in the repo. WDYT @straight-shoota ?

**Comment by straight-shoota** [comment]
Yeah, it's a library shard, so lock file doesn't need and probably shouldn't be checked in.

**Comment by kachick** [comment]
Thank you!
So https://github.com/kemalcr/spec-kemal/pull/20/commits/fcbaf2482474648e4f7349b5d180f22d23c8fe68 is correct understanding?

**Review by sdogruyol — APPROVED** [review]

**Comment by sdogruyol** [comment]
Thank you @kachick

**Comment by kachick** [comment]
Thank you!

**Pull request merged**
